// <auto-generated />
using Instituto.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Instituto.Datos.Migrations
{
    [DbContext(typeof(InstitutoDbContext))]
    partial class InstitutoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Instituto.Entidades.Alumno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Alumno");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Correo = "pepe@gmail.com",
                            Edad = 10,
                            Estado = true,
                            Nombre = "Pepe"
                        },
                        new
                        {
                            Id = 2,
                            Correo = "juan@gmail.com",
                            Edad = 10,
                            Estado = true,
                            Nombre = "Juan"
                        },
                        new
                        {
                            Id = 3,
                            Correo = "pedro@gmail.com",
                            Edad = 10,
                            Estado = true,
                            Nombre = "Pedro"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
